### PR TITLE
(svelte) - Refactor OperationStore update logic to be more granular

### LINKED ISSUE #1678: (svelte) - assigning context only retriggers execution once
urql version & exchanges:

Using `@urql/svelte` v1.2.2

**Steps to reproduce**

Attempt to use the following method to refresh/refetch/reexecute a query **more than once:** https://formidable.com/open-source/urql/docs/basics/svelte/#reexecuting-queries

**Expected behavior**

The query is re-executed each time `refresh` is called

**Actual behavior**

The query is only executed the first time, and subsequent calls to `refresh` fail to trigger a backend request

### PR DESCRIPTION
**Pull request by kitten**
Resolve #1678

## Summary

This changes the internal logic of `operationStore` to make updates more granular, which prevents accidental updates when nothing has actually changed. It also updates the `operations`' sources to check the identity of `context` instead of doing a deep comparison. These changes together will allow for more granular updates of the operations.

Additionally, this PR also adds a `reexecute` method to the stores, which allows the context value to be force-changed.

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]

File: packages/svelte-urql/src/internal.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 export const _contextKey = '$$_urql';
-export const _storeUpdate = new Set<object>();
+export const _storeUpdate = new WeakSet<object>();
```
Comment (mattfysh) [inline packages/svelte-urql/src/internal.ts:2]: Interesting, haven't heard of `WeakSet` - how does it affect the store update?
