### PR TITLE
Fix dedup ignoring torn down query operations

### LINKED ISSUE #280: Previously canceled queries are not refetched, but fetching is true
You can try it here https://codesandbox.io/s/tender-hodgkin-5xiqh by changing the input before the query finishes (for example 1 -> 2 -> 3 -> 2)

Version 1.1.0

### PR DESCRIPTION
**Pull request by kitten**
Fix #280 

When a query was torn down, the dedup exchange wasn't
removing its key from the inFlight keys.

This was causing us to ignore torn down queries forever.

### CODE REVIEW

File: src/exchanges/dedup.ts [hunk 1]
```diff
@@ -1,32 +1,36 @@
...
+    const isInFlight = inFlightKeys.has(key);
+    inFlightKeys.add(key);
+    return !isInFlight;
+  };
 
-            if (!hasInFlightOp) {
-              inFlight.add(key);
-            }
+  const afterOperationResult = ({ operation }: OperationResult) => {
+    inFlightKeys.delete(operation.key);
```
Comment (andyrichardson) [inline src/exchanges/dedup.ts]: Is there a reason for not having this inline?

Comment (kitten) [reply src/exchanges/dedup.ts]: Just to clean it up; I thought having names like `afterOperationResult` could help when someone's trying to figure out how those work
