### PR TITLE
(debug) - Dispatch network debug events consistently

### LINKED ISSUE #777: Incorrect data attribute on fetch debug events
## About

A `fetchResponse` event should return the successful JSON response from a successful fetch request. Currently it returns an _OperationResult_.

A `fetchError` event should return the JSON response from a failed fetch request. Currently it returns an _OperationResult_.

### PR DESCRIPTION
**Pull request by andyrichardson**
Fix #777

## About

Provide "raw" json to fetch debugging events

### CODE REVIEW

**Comment by kitten** [comment]
See: https://github.com/FormidableLabs/urql/pull/778#discussion_r417542504

File: packages/core/src/internal/fetchSource.ts [hunk 1]
```diff
@@ -24,11 +35,33 @@ const executeFetch = (
       if (!('data' in result) && !('errors' in result)) {
         throw new Error('No Content');
       }
+      dispatchDebug({
```
Comment (kitten) [inline packages/core/src/internal/fetchSource.ts:38]:
```suggestion
      }

      dispatchDebug({
```
