### PR TITLE
Fix node-resolution for Webpack

### LINKED ISSUE #640: mjs changes broke builds using create-react-app
After upgading to the latest urql + graphcache i get the following errors

./node_modules/@urql/exchange-graphcache/dist/urql-exchange-graphcache.esm.mjs
Can't import the named export 'buffer' from non EcmaScript module (only default export is available)

### LINKED ISSUE #644: Issue: Next js build failure (Can't import named export `Provider`)
Attempting to build urql with next js,i receive the following errors depending on how the app is set up:

`Can't import the named export 'concat' from non EcmaScript module (only default export is available)`

`Can't import the named export 'Provider' from non EcmaScript module (only default export is available)`

**urql version**
1.10.3

** nextjs version **
9.3.0

**Steps to reproduce**
https://github.com/skene/nextjs-with-urql

**Expected behavior**

build successfully.

**Actual behavior**
fails on build.

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Resolve #644 
Resolve #640 

This fixes a quirk in webpack when entering a module it would transition to using the `pkg.json[main]` for the rest of the resolution path.

### CODE REVIEW

File: scripts/prepare/index.js [hunk 1]
```diff
@@ -34,12 +34,12 @@ invariant(
 );
 
 invariant(
-  path.normalize(pkg.main) === `dist/${name}.cjs.js`,
+  path.normalize(pkg.main) === `dist/${name}.js`,
```
Comment (kitten) [inline scripts/prepare/index.js]:
```suggestion
  path.normalize(pkg.main) === `dist/${name}`,
```
