### PR TITLE
Ensure that state changes are applied immediately on mount

### LINKED ISSUE #209: useMutation value should be constant
I'm using a useMutation hook in a parent component, and passing the result down to a child component as the only prop. The child component rerenders whenever the parent rerenders. This means that the result value from useMutation keeps changing. It would be better if it were constant so that the child didn't rerender.

### LINKED ISSUE #245: `fetching` initially `false`?
All the documentation and code examples suggest if you check that `fetching` is `true` and `error` is falsey then you can assume `data` is not null.

e.x.

```
const YourComponent = () => {
  const [{ fetching, data }] = useQuery({ query: `{ todos { id } }` });
  return fetching ? <Loading /> : <List data={data.todos} />;
};
```

https://github.com/FormidableLabs/urql#quick-start-guide

However, that's not what I'm seeing. `fetching` is initially `false`:

Screenshot 2019-05-31 10 43 54

This happens for both the `Query` component and `useQuery` hook. Unless you explicitly check that `data` is not null then these examples will crash.

Or am I missing something?

Version: 1.0.5

### PR DESCRIPTION
**Pull request by kitten**
Fix #245
Fix #209 (See 17feeca)

It seems that in the current version React does
trigger *two* renders in our case.

We call executeQuery immediately which has a couple
of setStates. These are batched, it seems, but
do trigger a second update of the underlying
component, which is a shame.

Instead, we know that the initial executeQuery can
just safely merge its results into the initial
state, if it's during the initial mount.

This is why useImmediateState is added, which does
just that. Not the nicest way to solve this, but
the safest until React ships batched updates by
default.

This is basically a solution that will continue to
ensure that we won't have to add any state-related
stuff outside of `executeQuery`

### CODE REVIEW

**Comment by kitten** [comment]
cc @JoviDeCroock fyi: We still get a double render on mount since it seems that React will schedule a batched update on setState during initial mount instead of aborting to render that component, so this makes set State mutable during initial mount

File: src/hooks/useImmediateState.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+type SetStateAction<S> = S | ((prevState: S) => S);
+type SetState<S> = (action: SetStateAction<S>) => void;
+
+export const useImmediateState = <S extends {}>(init: S): [S, SetState<S>] => {
+  const isMounted = useRef(false);
+  const initialState = useRef<S>({ ...init });
+  const [state, setState] = useState<S>(initialState.current);
+
+  const updateState: SetState<S> = useCallback((action: SetStateAction<S>) => {
+    // If the component is currently before its initial mount, update
```
Comment (JoviDeCroock) [inline src/hooks/useImmediateState.ts]: For this comment shouldn't it be !isMounted.current?

File: src/hooks/useImmediateState.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    // the state immediately
+    if (isMounted.current) {
+      setState(action);
```
Comment (JoviDeCroock) [inline src/hooks/useImmediateState.ts]: so we set the potential function as state? Sorry if this question is weird trying to grasp it

File: src/hooks/useImmediateState.ts (hunk 1 above)
Comment (kitten) [reply src/hooks/useImmediateState.ts]: Oh the comment goes for the entire block; I'll pull it out of useCallback to clarify

File: src/hooks/useImmediateState.ts (hunk 2 above)
Comment (kitten) [reply src/hooks/useImmediateState.ts]: If we're in "will mount" basically we don't call setState and update the state mutably

Comment (JoviDeCroock) [reply src/hooks/useImmediateState.ts]: Oh, yes good point thanks for clarifying.

File: src/hooks/useImmediateState.ts (hunk 1 above)
Comment (JoviDeCroock) [reply src/hooks/useImmediateState.ts]: Ah allright, sorry got confused

Comment (kitten) [reply src/hooks/useImmediateState.ts]: No worries 👌 I'll add more comments

File: src/hooks/useImmediateState.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+type SetStateAction<S> = S | ((prevState: S) => S);
+type SetState<S> = (action: SetStateAction<S>) => void;
+
+export const useImmediateState = <S extends {}>(init: S): [S, SetState<S>] => {
+  const isMounted = useRef(false);
+  const initialState = useRef<S>({ ...init });
+  const [state, setState] = useState<S>(initialState.current);
+
+  const updateState: SetState<S> = useCallback((action: SetStateAction<S>) => {
```
Comment (andyrichardson) [inline src/hooks/useImmediateState.ts]: It looks like this does the following:
 - on first render
 - hijack `setState` call
 - uses mutation to update state value

Is that the case?

Comment (kitten) [reply src/hooks/useImmediateState.ts]: Ehhh, yes if you mean wrapping it by hijacking 👍😅

Comment (andyrichardson) [reply src/hooks/useImmediateState.ts]: Updated!

I found this pretty tricky to understand but I see what you're doing now. I think the same could be achieved by currying the executeQuery function and passing in:
 - A mutation setState function on initial render
 - The actual setState function on further renders

That would get rid of the need for an abstraction.

```tsx
const useQuery = () => {
    const isMounted = useRef(false);
    const initialState = useRef({ ... });
    const [state, setState] = useState(initialState);

    const updateState = useMemo(() => isMounted.current ? setState : (arg) => Object.assign(initialState, arg), [isMounted.current]);

    const executeQuery = useMemo(() => doExecuteQuery(updateState), [updateState])
    
    // ...
}

const doExecuteQuery = (setState, otherArgs) => () => // ...
```

Comment (kitten) [reply src/hooks/useImmediateState.ts]: It's not quite the same as you'd then trigger an update since `executeQuery` changes, since `updateState` changes after `initialMount` changes... yea, long chain of stuff happening. This is also not a deterministic update since it's depending on a ref, which means we get an unexpected query on the next update, whenever it comes 😅 anyway, since this is not about the code snippet:

I wouldn't inline this as the abstraction is nice imho; I think it reduces the amount of complexity for external contributors since they're just looking at drop-in replacements for `useEffect` and `useState` that they can assume to work the same.

Given that all bugs / things we've now fixed are really subtle variations on how one would usually write these features or this behaviour, the hooks ensure that we can continue to write them normally, mostly/hopefully bug-free, without making our code take on more concerns.

**Comment by kitten** [comment]
@andyrichardson Added some tests for `useImmediateState` and an additional one for `useImmediateEffect`. They should both ensure that these hooks behave as we expect, so like a normal `useState` and `useEffect` respectively apart from the special behaviour on initial mount.

File: src/hooks/useImmediateState.ts [hunk 4]
```diff
@@ -0,0 +1,33 @@
+import { useRef, useEffect, useState, useCallback } from 'react';
+
+type SetStateAction<S> = S | ((prevState: S) => S);
+type SetState<S> = (action: SetStateAction<S>) => void;
+
+/** This is a drop-in replacement for useState, limited to object-based state. During initial mount it will mutably update the state, instead of scheduling a React update using setState */
+export const useImmediateState = <S extends {}>(init: S): [S, SetState<S>] => {
+  const isMounted = useRef(false);
+  const initialState = useRef<S>({ ...init });
```
Comment (andyrichardson) [inline src/hooks/useImmediateState.ts]: Just had a thought about this - we aren't using this object anywhere other than initial render so the use of useRef might be misleading/unnecessary.

Comment (kitten) [reply src/hooks/useImmediateState.ts]: We are using this as a throwaway target for unmounted setState calls but otherwise yea, not really needed on client-side.

But during React server-side rendering this can actually matter, since some calls will reset component rendering and start over, which means that since our client is external we might get subtly different results.

It probably doesn't matter but that's why I chose to use refs.

File: src/hooks/useImmediateState.ts [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+  const [state, setState] = useState<S>(initialState.current);
+
+  // This wraps setState and updates the state mutably on initial mount
+  // It also prevents setting the state when the component is unmounted
+  const updateState: SetState<S> = useCallback((action: SetStateAction<S>) => {
+    if (isMounted.current) {
+      setState(action);
+    } else if (typeof action === 'function') {
```
Comment (andyrichardson) [inline src/hooks/useImmediateState.ts]: Can we return from these conditions rather than having to parse multiple conditions.

```tsx
if (isMounted.current) {
  return setState(action);
}

const actionValue = typeof action === "function" ? action(initialState.current) : action;
Object.assign(initialState.current, actionValue);
```

Comment (kitten) [reply src/hooks/useImmediateState.ts]: Doesn't really make a difference though so not to be too bikesheddy, but since we just follow some loose eslint rules,
you can always change it to what you prefer when you happen to refactor or rewrite this part of the codebase 😅

File: .eslintrc.json [hunk 6]
```diff
@@ -25,7 +25,12 @@
     "@typescript-eslint/no-explicit-any": "off",
     "@typescript-eslint/array-type": "off",
     "react-hooks/rules-of-hooks": "error",
-    "react-hooks/exhaustive-deps": "warn",
+    "react-hooks/exhaustive-deps": [
+      "warn",
+      {
+        "additionalHooks": "useImmediateEffect"
```
Comment (parkerziegler) [inline .eslintrc.json]: ❤️this really is such a nice surprise!

File: src/hooks/useImmediateEffect.test.ts [hunk 7]
```diff
@@ -8,14 +8,37 @@ it('calls effects immediately on mount', () => {
...
-  renderHook(() => useImmediateEffect(effect, [effect]));
 
-  expect(effect).toHaveBeenCalledTimes(1);
-  expect(effect).toHaveBeenCalledTimes(1);
+  renderHook(() => {
+    useImmediateEffect(effect, [effect]);
+    expect(effect).toHaveBeenCalledTimes(1);
+  });
 
+  expect(effect).toHaveBeenCalledTimes(1);
```
Comment (parkerziegler) [inline src/hooks/useImmediateEffect.test.ts]: Not sure I totally get the logic behind the second `.toHaveBeenCalledTimes` here. As I read this, I'd expect `useImmediateEffect` to get called once on first render (which we verify with the first assertion), then I wouldn't expect us to need to assert again. So can you explain the reasoning behind having this second assertion?

Comment (kitten) [reply src/hooks/useImmediateEffect.test.ts]: react-hooks-testing-library had this weird thing where it'd execute effects after the initial mount automatically.

So if the initial effect was actually executed after manual call inside the initial mount, we'd see two calls here

File: src/hooks/useImmediateEffect.ts [hunk 8]
```diff
@@ -1,4 +1,6 @@
-import { useRef, useEffect, useCallback } from 'react';
+/* eslint-disable react-hooks/exhaustive-deps */
```
Comment (parkerziegler) [inline src/hooks/useImmediateEffect.ts]: Is this intentional? Seems somewhat dangerous and easy to overlook. What would you say to just using `eslint-disable-next-line` where needed?

Comment (parkerziegler) [inline src/hooks/useImmediateEffect.ts]: What would you say to moving this above the dependency array and adding a comment on why we don't want `effect` included. I personally am interested to know why (looks like you can't do `[...changes, effect]` or `changes.concat([effect]);`). It seems like `effect` could potentially get stale if not included in the dependency array.

Comment (kitten) [reply src/hooks/useImmediateEffect.ts]: The effect itself can get stale in fact, but this follows React's logic. So we'll only update when the specified effects update not the passed closure. I think since this is quite small I just didn't add it inline 😅

File: src/hooks/useImmediateState.ts [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+      const update = (action as any)(initialState.current);
+      Object.assign(initialState.current, update);
```
Comment (parkerziegler) [inline src/hooks/useImmediateState.ts]: Alright, totally could be missing something, but don't we need to do the assignment to `initialState.current` here to ensure the mutable ref gets updated, i.e.

```
initialState.current = Object.assign(initialState.current, update)
```

Comment (kitten) [reply src/hooks/useImmediateState.ts]: Nah, the first argument is being assigned to mutably 😀

File: src/hooks/useQuery.ts [hunk 10]
```diff
@@ -28,61 +29,54 @@ export type UseQueryResponse<T> = [
...
         unsubscribe.current = noop;
         return;
+      } else {
+        setState(s => ({ ...s, fetching: true }));
       }
 
-      setState(s => ({ ...s, fetching: true }));
-
-      const [teardown] = pipe(
+      [unsubscribe.current] = pipe(
```
Comment (parkerziegler) [inline src/hooks/useQuery.ts]: A bit confused by how this works. Is this array destructuring also capable of reassignment, i.e. this basically turns into:

```
const [teardown] = pipe(/* stuff */)
unsubscribe.current = teardown;
```

It seems like a dope feature of TS if true.

File: src/hooks/useImmediateState.ts (hunk 9 above)
Comment (parkerziegler) [reply src/hooks/useImmediateState.ts]: Ah right, I forgot that `Object.assign` mutates the original object 👍

File: src/hooks/useQuery.ts (hunk 10 above)
Comment (kitten) [reply src/hooks/useQuery.ts]: Yep, works in pure JS as well, since the destructuring target can almost be any expression afaik
