### PR TITLE
Fix missing package.json entry in exports field

### LINKED ISSUE #708: Error building with latest graphcache and cra
Hi I get the following error when building cra app with the latest graphcache

```
./node_modules/@urql/exchange-populate/dist/urql-exchange-populate.mjs
Attempted import error: 'visitWithTypeInfo' is not exported from 'graphql/utilities/TypeInfo'.
```

Thanks

### LINKED ISSUE #770: svelte: error path package.json
Hi,

I'm having a hard time importing the library. I'm not sure what the problem is, since it seems to work correctly for others.

Here's the error:

```
~/code/svelte/my-svelte-project
➜ yarn dev
yarn run v1.22.4
warning package.json: No license field
$ rollup -c -w
rollup v1.32.1
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /Users/k/code/svelte/my-svelte-project/node_modules/@urql/svelte/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/k/code/svelte/my-svelte-project/node_modules/@urql/svelte/package.json
    at applyExports (internal/modules/cjs/loader.js:492:9)
    at resolveExports (internal/modules/cjs/loader.js:508:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.requireRelative.resolve (/Users/k/code/svelte/my-svelte-project/node_modules/require-relative/index.js:30:17)
    at tryResolve (/Users/k/code/svelte/my-svelte-project/node_modules/rollup-plugin-svelte/index.js:50:19)
    at Object.resolveId (/Users/k/code/svelte/my-svelte-project/node_modules/rollup-plugin-svelte/index.js:177:21)
    at /Users/k/code/svelte/my-svelte-project/node_modules/rollup/dist/shared/node-entry.js:13117:25
```
 
I'm using @urql/svelte: 0.2.2

**Steps to reproduce**

```
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
yarn add @urql/svelte graphql
# Add 'import { initClient } from "@urql/svelte";' in src/App.svelte
yarn dev
```

I'm using node 14 not sure if it's causing issues ? Other than that my setup is pretty normal.

**Expected behavior**

A successful build

**Actual behavior**

Cannot build

EDIT: Actually if I add `"./package.json": "./package.json",` in the `exports` in `package.json`, will complain about the same thing but the core package and if I add it there, same thing in the wonka package. After that it seems to be working, at least it builds.

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fix #770 
Fix #708

## Summary

Adds the `./package.json` exports entry for Node 14.

## Set of changes

- add `./package.json` to exports

### CODE REVIEW

**Comment by kitten** [comment]
Shouldn’t this be fixed in Rollup, or the Svelte plugin?
Seems to me like this is something that is easy to work around by telling people to remain node 12/13 and to wait for a patch on their end, rather than us bumping all packages (including potentially Wonka) again 😅

I think this is also a use-case that for some reason is explicitly not supported by the spec

File: scripts/rollup/settings.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ export const name = normalize(pkg.name);
 
 export const sources = pkg.exports
   ? Object.keys(pkg.exports).map(entry => {
+    if (entry === './package.json') return undefined;
```
Comment (kitten) [inline scripts/rollup/settings.js:17]: Can we add a validation step for it existing in every package?

File: .changeset/flat-buses-develop.md [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+'@urql/exchange-multipart-fetch': patch
+'@urql/exchange-persisted-fetch': patch
+'@urql/exchange-populate': patch
+'@urql/exchange-retry': patch
+'@urql/core': patch
+'@urql/preact': patch
+'@urql/svelte': patch
+---
+
+Add the package.json entry to the exports for Node 14
```
Comment (kitten) [inline .changeset/flat-buses-develop.md:12]:
```suggestion
Add a `"./package.json"` entry to the `package.json`'s `"exports"` field for Node 14. This seems to be required by packages like `rollup-plugin-svelte` to function properly.
```
